version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - financial-news-network
    env_file:
      - .env
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
      # Add a placeholder for the API key that will be populated from .env
      - NEWS_API_KEY=${NEWS_API_KEY:-default_value_for_development}
    volumes:
      - ./backend/data:/app/backend/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - financial-news-network
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - PORT=5000
      - BACKEND_URL=http://backend:8000
      - STREAMLIT_SERVER_HEADLESS=true
      # Any additional frontend-specific environment variables can be added here
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  financial-news-network:
    driver: bridge

volumes:
  data_volume:
    driver: local
