services:
  - type: web
    name: financial-news-backend
    env: python
    plan: free
    buildCommand: pip install -r project_requirements.txt
    startCommand: python run_backend.py
    healthCheckPath: /health
    # Use Render's default PORT environment variable
    # Explicitly tell our app to use this port
    envVars:
      - key: PORT
        sync: false # This means use Render's PORT value
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FORMAT
        value: json
      - key: MODEL_VERSION
        value: rule-based-v1
      - key: NEWS_API_KEY
        value: 7b1d5085942941a381128b6349c59e19
        # The NewsAPI key is defined directly in the render.yaml file
        # Since this is a demo project with a publicly available key

  - type: web
    name: financial-news-frontend
    env: python
    plan: free
    buildCommand: pip install -r project_requirements.txt
    startCommand: streamlit run run_frontend.py --server.port $PORT --server.headless true --server.address 0.0.0.0
    envVars:
      - key: BACKEND_URL
        value: https://financial-news-backend-93w8.onrender.com
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
