apiVersion: apps/v1
kind: Deployment
metadata:
  name: financial-news-backend
  labels:
    app: financial-news
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: financial-news
      tier: backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: financial-news
        tier: backend
    spec:
      containers:
      - name: backend
        image: username/financial-news-backend:latest
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
        - name: LOG_LEVEL
          value: "INFO"
        - name: LOG_FORMAT
          value: "json"
        - name: NEWS_API_KEY
          valueFrom:
            secretKeyRef:
              name: api-keys
              key: news-api-key
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 15
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: financial-news-backend
  labels:
    app: financial-news
    tier: backend
spec:
  selector:
    app: financial-news
    tier: backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP