apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  # Values need to be base64 encoded
  # Example: echo -n "your-api-key" | base64
  news-api-key: N2IxZDUwODU5NDI5NDFhMzgxMTI4YjYzNDljNTllMTk=  # This is just a placeholder, replace with real key